### ISSUE TITLE
Streams don't load on Firefox Nightly

### ISSUE THREAD

**Issue by progamer63** [younesaassila/ttv-lol-pro#107] opened 2023-03-27 06:44 UTC
Debugging addon gives a "Reading manifest: Warning processing update_url: An unexpected property was found in the WebExtension manifest." warning. Stream video feeds are entirely blacked out.

**Comment by younesaassila** [comment] 2023-03-27 11:01
1. `update_url` key warning is expected. Doesn't cause any issues.
1. What Firefox version? Works perfectly on Release and Dev editions for me.

**Comment by progamer63** [comment] 2023-03-27 20:35
It seems to be working now. I'm on Nightly, Version 113.0a1 (2023-03-26). Maybe it was just a temporary thing?

**Comment by s-crypt** [comment] 2023-03-27 23:27
I am experiencing the same issue on Firefox Nightly 113.0a1 (2023-03-27) and it has been like this for a couple of days. The stream wont load, it is just stuck in a loading/buffering screen. Disabling the extension and refreshing the page has the stream work. 

I cannot find anything in the browser console that is preventing the stream from loading.

The only logs in the console from the extension are

```
[TTV LOL PRO] Content script running.
[TTV LOL PRO] Page script running.
```

**Comment by younesaassila** [comment] 2023-03-28 00:58
Can indeed reproduce on Nightly. The temporary fix is to disable the "Reset player on midroll" feature.
I think this is due to some Nightly bug but I'll keep an eye on it in case this behavior ends up in the Release version of Firefox.

**Comment by younesaassila** [comment] 2023-04-12 02:35
Seems to be a Nightly-only bug! This doesn't happen in the 113 Beta:
![image](https://user-images.githubusercontent.com/47226184/231333047-f8432c61-4705-4ca7-afa4-bd6fa3db6083.png)
but still does in 114 Nightly

**Comment by younesaassila** [comment] 2023-05-13 16:22
Closing this issue since it was due to the "Reset player on midroll" feature which is now deprecated.

**Closed by younesaassila** 2023-05-13 16:22 UTC
Labels: bug, v1
