### ISSUE TITLE
Increased error rate (error #2000)

### ISSUE THREAD

**Issue by MisterSheeple** [younesaassila/ttv-lol-pro#179] opened 2023-06-09 23:28 UTC
**Describe the bug**
After watching a stream for a few minutes, the stream displays error 2000 and upon refreshing, the stream works fine for a few more minutes before displaying the error again.

**To Reproduce**
1. Install TTV LOL PRO v2
2. Open a stream
3. After a little while, the stream stops and displays error 2000 and asks you to refresh the stream.
4. Upon refresh, the stream works fine for a while until displaying the error again.

**Expected behavior**
No error.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version 114.0

**Comment by younesaassila** [comment] 2023-06-09 23:54
@MisterSheeple Are you using the default proxy?

**Comment by MisterSheeple** [comment] 2023-06-10 01:38
> @MisterSheeple Are you using the default proxy?

Yes.

**Comment by younesaassila** [comment] 2023-06-10 08:36
Could you reproduce the bug with the browser console open (F12) and post a screenshot of the console when error #2000 shows up? Thanks

**Comment by JohannesKnopp** [comment] 2023-06-10 12:04
Hi, I am encountering the same issue, also using the default proxy, here a screenshot of the browser console when the error happens:
![Console Screenshot](https://github.com/younesaassila/ttv-lol-pro/assets/27307260/e0e037d1-2587-459f-9ee1-8eea8a09d243)

OS: Pop!_OS
Browser: Firefox 114.0
TTV LOL PRO: 2.0.0 installed as temporary add-on

**Comment by younesaassila** [comment] 2023-06-11 21:36
Is this bug still happening? If so, is it happening reliably, like every time?
@MisterSheeple @JohannesKnopp

**Comment by MisterSheeple** [comment] 2023-06-11 22:26
> Is this bug still happening? If so, is it happening reliably, like every time?

I'm having some PC troubles at the moment so I'll get back to you when I'm able to boot again.

**Comment by JohannesKnopp** [comment] 2023-06-13 17:26
> Is this bug still happening? If so, is it happening reliably, like every time?

Haven't had any ads / errors the last 2 days, but I've also coincidentally installed pi-hole on my end approximately  2 days ago, so I'm not really sure what "fixed" the problem for me (whether it was pi-hole or something else).

**Comment by ghost** [comment] 2023-06-14 05:06
This is still currently still an issue, also happening in chrome as well, and seems at random. Plays anywhere from 3 seconds to 2 minutes then get this error. Something I have noticed though, it does it more when I switch to another tab, not sure if that would have anything to do with it or not or how you would test that. 

OS: Windows 11
Browser: Chrome
Version: 114.0.5735.134 (Official Build) (64-bit)

**Comment by zGato** [comment] 2023-06-15 00:31
> This is still currently still an issue, also happening in chrome as well, and seems at random. Plays anywhere from 3 seconds to 2 minutes then get this error. Something I have noticed though, it does it more when I switch to another tab, not sure if that would have anything to do with it or not or how you would test that.
> 
> OS: Windows 11 Browser: Chrome Version: 114.0.5735.134 (Official Build) (64-bit)

Tabbing or in any way making the client stop the stream or reset the player will probably trigger error #2000 on peak hours due to limited amout of slots on Chrome. Active connections do not get any issues, but newer may need to click the red "Reload" button until it lets you in.

As always, Firefox users don't have slot limitations. Consider making the change :)

**Comment by ghost** [comment] 2023-06-15 03:17
> > This is still currently still an issue, also happening in chrome as well, and seems at random. Plays anywhere from 3 seconds to 2 minutes then get this error. Something I have noticed though, it does it more when I switch to another tab, not sure if that would have anything to do with it or not or how you would test that.
> > 
> > OS: Windows 11 Browser: Chrome Version: 114.0.5735.134 (Official Build) (64-bit)
> 
> Tabbing or in any way making the client stop the stream or reset the player will probably trigger error #2000 on peak hours due to limited amout of slots on Chrome. Active connections do not get any issues, but newer may need to click the red "Reload" button until it lets you in.
> 
> As always, Firefox users don't have slot limitations. Consider making the change :)

Nevertheless, it's still happening even without changing tabs, but see it more when I do. Also, just moving to Firefox doesn't fix the issue for the people who need to use chrome and can't switch. This issue should be at least attempted to be fixed for both browsers.

**Comment by zGato** [comment] 2023-06-15 06:23
> > > This is still currently still an issue, also happening in chrome as well, and seems at random. Plays anywhere from 3 seconds to 2 minutes then get this error. Something I have noticed though, it does it more when I switch to another tab, not sure if that would have anything to do with it or not or how you would test that.
> > > OS: Windows 11 Browser: Chrome Version: 114.0.5735.134 (Official Build) (64-bit)
> > 
> > 
> > Tabbing or in any way making the client stop the stream or reset the player will probably trigger error #2000 on peak hours due to limited amout of slots on Chrome. Active connections do not get any issues, but newer may need to click the red "Reload" button until it lets you in.
> > As always, Firefox users don't have slot limitations. Consider making the change :)
> 
> Nevertheless, it's still happening even without changing tabs, but see it more when I do. Also, just moving to Firefox doesn't fix the issue for the people who need to use chrome and can't switch. This issue should be at least attempted to be fixed for both browsers.

Where are you from? (EU/NA/SA...)

**Comment by ghost** [comment] 2023-06-15 06:25
> > > > This is still currently still an issue, also happening in chrome as well, and seems at random. Plays anywhere from 3 seconds to 2 minutes then get this error. Something I have noticed though, it does it more when I switch to another tab, not sure if that would have anything to do with it or not or how you would test that.
> > > > OS: Windows 11 Browser: Chrome Version: 114.0.5735.134 (Official Build) (64-bit)
> > > 
> > > 
> > > Tabbing or in any way making the client stop the stream or reset the player will probably trigger error #2000 on peak hours due to limited amout of slots on Chrome. Active connections do not get any issues, but newer may need to click the red "Reload" button until it lets you in.
> > > As always, Firefox users don't have slot limitations. Consider making the change :)
> > 
> > Nevertheless, it's still happening even without changing tabs, but see it more when I do. Also, just moving to Firefox doesn't fix the issue for the people who need to use chrome and can't switch. This issue should be at least attempted to be fixed for both browsers.
> 
> Where are you from? (EU/NA/SA...)

US.

**Comment by zGato** [comment] 2023-06-15 06:31
Add me on discord please: `zgato_`
Or: `zGato | Marc#7399`

**Closed as not planned** 2023-06-26 16:31 UTC
Labels: bug, help wanted

**Comment by ipisano** [comment] 2023-07-21 17:08
I'm having the same exact issue described by the user, I watch twitch exclusively while doing other stuff so I'm always tabbed out of my browser or in another tab. I already tried deleting cookies/cache, reinstalling the extension, resetting uBlock settings (because I used to use VAFT, just in case I didn't clean it up properly) but the error persists. At the moment I'm using an android emulator with a modded app as a workaround, but it's not ideal when gaming because my CPU is already kinda getting a bit grey in the hair compared to my GPU and the performance decrease when running the emulator is evident
