### ISSUE TITLE
After installing version 2.0, there is no network (Kaspersky)

### ISSUE THREAD

**Issue by YheonYeung** [younesaassila/ttv-lol-pro#167] opened 2023-06-07 12:01 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [win11 22H2]
 - Browser [chrome,]
 - Version [114.0.5735.110_64bit]

**Smartphone (please complete the following information):**

**Additional context**
I have to use "clash for windows" to browse the Internet, 1.9.3 has no problem, but version 2.0 will cause no internet.

**Comment by younesaassila** [comment] 2023-06-07 14:35
Hey could you describe more precisely what the issue is about? By no internet do you mean no internet at all like you can't even access Google? Or do you mean just Twitch? If it is just Twitch is it a blank webpage or is it the Twitch ghost icon? Thanks

**Comment by juliocoliveira** [comment] 2023-06-07 15:23
![image](https://github.com/younesaassila/ttv-lol-pro/assets/6606725/6e749941-7bff-409a-89fd-a67eaa9379e0)
Same here updated version just installed, emptied cache, relaunched app, did a reset extension's settings to default nothing seems to work:
TTV LOL PRO v2.0.0
- Install type: normal
- Browser: Firefox 115.0
- OS: Windows NT 10.0
- Passport enabled: true
- Is laissez-passer: false
- Optimized proxies enabled: true
- Optimized proxies: ["dev.ttvlolpro.perfprod.com:2023"]
- Normal proxies: []
- Last ad log entry: N/A

**Comment by juliocoliveira** [comment] 2023-06-07 15:24
It's Kaspersky Injection bug back again with revenge.  :-D

**Comment by younesaassila** [comment] 2023-06-07 15:25
> It's Kaspersky Injection bug back again with revenge. :-D

Yeah I'm wondering if OP (@YheonYeung) also has Kaspersky. Their bug description is not very clear though.

**Comment by younesaassila** [comment] 2023-06-07 15:31
Kaspersky really makes me mad with this script injection stuff. Why do they modify request headers instead of idk... alerting the user a third-party might be intercepting requests with the option to "Allow"???

**Comment by juliocoliveira** [comment] 2023-06-07 15:38
I tested, and retested, it's confirmed, it's the same bug back again.
Disabling the injecting script in Kaspersky plus fixes this bug.
![image](https://github.com/younesaassila/ttv-lol-pro/assets/6606725/362558d3-e094-488f-b2f5-8e3825f68bff)
Why they do the things their way I really don't know, This Injection is just a gimmick not that useful. Still I like to keep it enabled if possible.

**Comment by juliocoliveira** [comment] 2023-06-07 17:24
It's a gimmick that makes my firefox hang on loading if I disable it. So can't keep it disabled it seems.

**Comment by ghost** [comment] 2023-06-08 03:03
**v2 has been bypassed (note that this includes EVERY SINGLE PROXY Ever made, or that will Ever be made.)**

**Comment by YheonYeung** [comment] 2023-06-08 06:08
Since I am in the hell of communist China, I have to use clash for windows to browse Google, Twitch, etc. When I changed to version 2.0, it was like I didn't open this proxy software, and no web pages could be opened, except the communist China IP addresses webpage. I use the anti-virus software is NOD32 Antivirus 16.1.14.0.

**Comment by younesaassila** [comment] 2023-06-08 09:25
@YheonYeung I see what is the problem. When the extension loads it replaces the current proxy config. I'll fix that in the next update hopefully

**Comment by younesaassila** [comment] 2023-06-10 12:29
Closing this issue since Kaspersky bug is now fixed in 2.0.1. For the proxy/VPN issue, see #165

**Closed as completed by younesaassila** 2023-06-10 12:29 UTC
Labels: bug
