### ISSUE TITLE
Player reset *sometimes* fails

### ISSUE THREAD

**Issue by Mioni** [younesaassila/ttv-lol-pro#69] opened 2023-01-24 00:25 UTC
Hello, could you make the version 1.7.0 available? The version 1.7.1 is having problems when it resets and everything is black and does not start live anymore, I need to press F5 to get live back to normal. In the other version did not happen these problems.

Thanks!

**Comment by deaglenomics** [comment] 2023-01-24 03:27
@Mioni 
https://github.com/younesaassila/ttv-lol-pro/releases/tag/v1.7.0

**Comment by younesaassila** [comment] 2023-01-24 10:02
The player reset code of v1.7.0 is the exact same code as v1.7.1.
I think you're talking about v1.6.1, in which case the build is still available

**Comment by Mioni** [comment] 2023-01-24 16:42
The beta versions that you were making available were normal but now it gets all black when reset and the stream doesn't run I need to hit f5, I just wanted the beta version that you were making available.
I don't use VAFT scripts.

**Comment by younesaassila** [comment] 2023-01-24 18:19
Could you please provide a screenshot of your browser's console when that happens? That way I can try to fix the issue.

I you really want the latest v1.7.0 beta, you can compile it yourself, here's the corresponding commit: https://github.com/younesaassila/ttv-lol-pro/tree/944d1403cc065c760d723af94c667feca5003834

**Comment by Mioni** [comment] 2023-01-24 18:29
When this problem happens again I will post a screenshot.

**Comment by younesaassila** [comment] 2023-01-31 10:15
@Mioni Did this happen again since your last comment?

**Comment by Mioni** [comment] 2023-01-31 11:30
Not yet, it's being rare to reset the player now, when it happens I'll reopen it here.

**Comment by younesaassila** [comment] 2023-01-31 11:33
No problem, I'll reopen this issue in case someone else is experiencing the same problem, that way we have a common thread about it

**Comment by younesaassila** [comment] 2023-02-19 19:15
Closing this issue since the problem is supposedly gone. If anyone encounters a similar problem, please create a new issue.

**Closed by younesaassila** 2023-02-19 19:15 UTC
Labels: bug
