### ISSUE TITLE
Bro, the 2.0.1 version does not fix the problem of #167

### ISSUE THREAD

**Issue by YheonYeung** [younesaassila/ttv-lol-pro#186] opened 2023-06-13 08:41 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [win11 22H2]
 - Browser [chrome]
 - Version [114.0.5735.110_64bit]

**Smartphone (please complete the following information):**

**Additional context**
![2023-06-13_162959](https://github.com/younesaassila/ttv-lol-pro/assets/63342274/236f01fa-6153-4382-ae99-748c3563fbed)
![2023-06-13_163528](https://github.com/younesaassila/ttv-lol-pro/assets/63342274/c92318d4-2831-401c-a9f7-885946f4a665)
The problem is still there is no any network, when I turn off the plugin there is network.
I know that if you are in a network environment without DNS pollution, it must be difficult to restore this situation for testing.

**Comment by younesaassila** [comment] 2023-06-13 09:36
Duplicate of #165. Closing

**Closed as not planned by younesaassila** 2023-06-13 09:36 UTC
Labels: bug

**Comment by YheonYeung** [comment] 2023-06-13 12:37
What's the meaning? I use NOD32 but not Kaspersky, 1.9.3 is no problem, since 2.0, it conflicts with the proxy function of clash for windows, and 2.0.1 has not solved it. It’s not clear after closing it twice, if you don’t plan to fix it, I won’t bother you anymore.
![2023-06-13_204930](https://github.com/younesaassila/ttv-lol-pro/assets/63342274/4045e1e9-3b8b-493b-8120-7b558ff76681)

**Comment by younesaassila** [comment] 2023-06-14 13:26
@YheonYeung I know you don't use Kaspersky. Your OG issue had many comments related to Kaspersky which is why I considered it a Kaspersky issue.

I KNOW using VPNs and other proxies still conflict which is why #165 was created specifically for those.

Though from what research on the topic shows, it's impossible to use other proxies or VPNs when using Twitch and TTV LOL PRO v2, and since you told me you're affected by the GFW, it might be easier for you to look at client-side only solutions like the VAFT script.
